name: alphazed
description: "An engaging educational app that helps children learn the alphabet through interactive picture matching games."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1001

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.3.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^6.1.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.8.5
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/audio/letters/
    - assets/audio/words/
    - assets/audio/congrats/
    - assets/audio/other/
    - assets/audio/questions/
    - assets/audio/support/
    - assets/audio/temp/

# App icon configuration for both iOS and Android
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF" # Add this line for Android adaptive icons
  adaptive_icon_foreground: "assets/icons/app_logo.png" # Add this for Android adaptive icon foreground
  web:
    generate: true
    image_path: "assets/icons/app_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#4CC9F0"
  windows:
    generate: true
    image_path: "assets/icons/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_logo.png"

# Splash screen configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash_icon.png
  color_dark: "#121212"
  image_dark: assets/icons/splash_icon.png
  
  android_12:
    image: assets/icons/splash_icon.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/icons/splash_icon.png
    icon_background_color_dark: "#121212"
  
  web: false
  fullscreen: true
  
  # Reduce splash screen duration to minimize white screen perception
  android_gravity: center
  ios_content_mode: center
  android_screen_orientation: portrait
  
  # Keep splash screen longer until the app is fully loaded
  # This prevents the white screen from appearing
  branding: assets/icons/app_logo.png
  branding_mode: bottom
